# Generated by Django 4.1.4 on 2023-01-06 13:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pgs', '0002_rename_user_id_names_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Names',
            new_name='Users',
        ),
    ]
