# Generated by Django 4.1.4 on 2023-01-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0008_alter_users_brief_alter_users_date_alter_users_emil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%y/%m/%d/'),
        ),
    ]
