# Generated by Django 4.1.4 on 2023-01-09 10:21

from django.db import migrations, models
import pgs.models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0009_alter_users_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pgs.models.file_path),
        ),
    ]
