# Generated by Django 4.1.4 on 2023-01-12 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgs.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pgs', '0010_alter_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='forget_token',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfile',
            name='paper',
            field=models.FileField(upload_to=pgs.models.papers_path),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
