# Generated by Django 4.1.4 on 2023-01-15 17:03

from django.db import migrations, models
import pgs.models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0020_remove_users_forget_token_remove_users_token_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='paper',
            field=models.FileField(blank=True, upload_to=pgs.models.papers_path),
        ),
    ]
