# Generated by Django 4.1.4 on 2023-01-15 17:27

from django.db import migrations, models
import pgs.models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0022_alter_userfile_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='paper',
            field=models.FileField(blank=True, upload_to=pgs.models.papers_path),
        ),
    ]
