from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('working', views.working_page, name='working'),
    path('search', views.search, name='search'),
    path('info/<int:id>', views.info, name='info'),
    path('login', views.login_page, name='login'),
    path('logout', views.logout_page, name='logout'),
    path('singup', views.sign_up, name='singup'),
    path('reset-password', views.reset_passwords, name='reset-password'),
    path('reset-password-sent', views.reset_password_sent, name='reset-password-sent'),
    path('set-password/<token>', views.set_passwords, name='set-password'),
    path('invalid-token/<token>', views.invalid_token, name='invalid-token'),
     path('change-password', views.change_password, name='change-password'),
    path('change-password-success', views.change_password_success, name='change-password-success'),
    path('reset', views.reset, name='reset'),
    path('profile', views.user_profile, name='profile'),
    path('search-data', views.search_data, name='search-data'),
    path('get-search-data/<int:id>', views.get_search_data, name='get-search-data'),
    path('universty-data', views.university_data, name='universty-data'),
    path('colleges-data', views.colleg_data, name='colleges-data'),
    path('degrees-data', views.degree_data, name='degrees-data'),
    path('eligibles-data', views.eligible_data, name='eligibles-data'),
    path('file-upload', views.file_uploader, name='file-upload'),
    path('delete_image', views.delete_image, name='delete_image'),
    path('search-papers', views.search_papers, name='search-papers'),
    path('user-papers/id=<int:id>', views.user_file, name='user-papers'),
]
