# Generated by Django 4.1.4 on 2023-01-06 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eligible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(max_length=50)),
                ('paper', models.FileField(upload_to='papers/%y/%m/%d')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=20, unique=True)),
                ('college', models.ManyToManyField(to='pgs.colleges')),
                ('department', models.ManyToManyField(to='pgs.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_name', models.CharField(max_length=20, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state_of_supervisor', models.BooleanField(default=True)),
                ('state_of_examiner', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=254, null=True)),
                ('emil', models.CharField(max_length=254, null=True)),
                ('whatsup', models.CharField(max_length=254, null=True)),
                ('linkedin', models.CharField(max_length=254, null=True)),
                ('facebook', models.CharField(max_length=254, null=True)),
                ('twitter', models.CharField(max_length=254, null=True)),
                ('brief', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='photo/%y/%m/%d')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.colleges')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.departments')),
                ('eligible', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.eligible')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.specialty')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.universities')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
