# Generated by Django 4.1.4 on 2023-01-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='names',
            old_name='user_ID',
            new_name='user_id',
        ),
    ]
