# Generated by Django 4.1.4 on 2022-12-25 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=20)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.specialty')),
            ],
        ),
    ]
