# Generated by Django 4.1.4 on 2022-12-25 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0002_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Eligible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='University_Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branche', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.colleges')),
                ('university_branches', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.university_branches')),
            ],
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('e_mill', models.CharField(max_length=254, null=True)),
                ('state_of_supervisor', models.BooleanField(default=True)),
                ('state_of_examiner', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.colleges')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.departments')),
                ('eligible', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.eligible')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.specialty')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.universities')),
                ('university_branches', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgs.university_branches')),
            ],
        ),
    ]
