# Generated by Django 4.1.4 on 2023-01-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0003_rename_names_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
