# Generated by Django 4.1.4 on 2023-01-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0003_colleges_degree_eligible_university_branches_and_more'),
        ('pgs', '0005_users'),
    ]

    operations = [
    ]
