# Generated by Django 4.1.4 on 2023-01-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0006_merge_20230108_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colleges',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='universities',
            name='university_branches',
        ),
        migrations.AddField(
            model_name='universities',
            name='department',
            field=models.ManyToManyField(to='pgs.departments'),
        ),
        migrations.AddField(
            model_name='users',
            name='date',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='college_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='degree_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='departments',
            name='department_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='eligible',
            name='eligible_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='universities',
            name='college',
        ),
        migrations.AlterField(
            model_name='universities',
            name='university_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Names',
        ),
        migrations.DeleteModel(
            name='University_Branches',
        ),
        migrations.AddField(
            model_name='universities',
            name='college',
            field=models.ManyToManyField(to='pgs.colleges'),
        ),
    ]
