# Generated by Django 4.1.4 on 2023-01-14 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0017_news_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
