# Generated by Django 4.1.4 on 2023-01-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0018_users_token_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='token_date',
            field=models.DateTimeField(null=True),
        ),
    ]
