# Generated by Django 4.1.4 on 2023-01-14 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pgs', '0019_alter_users_token_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='forget_token',
        ),
        migrations.RemoveField(
            model_name='users',
            name='token_date',
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, null=True)),
                ('token_date', models.DateTimeField(null=True)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
